# Generated by Django 3.2.10 on 2022-03-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('wage', models.FloatField(default=2, max_length=8)),
            ],
        ),
    ]
