# Generated by Django 3.2.10 on 2022-06-01 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('pub_date', models.DateField()),
                ('authors', models.ManyToManyField(to='model.Emp')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.test')),
            ],
        ),
    ]
