# Generated by Django 3.2.10 on 2022-06-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_personnel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='password',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='wage',
            new_name='salary',
        ),
    ]
